/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.graph.ui;

import br.beholder.graph.controller.MainPanelController;
import br.beholder.graph.core.algoritmos.search.SearchAlgorithmFactory;
import br.beholder.graph.ui.utils.ColorController;
import br.beholder.graph.ui.webLaf.WeblafUtils;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author lite
 */
public class MainPanel extends javax.swing.JPanel {
    private MainPanelController controller;
    private boolean buttonsEnabled;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        configura();
        controller=new MainPanelController(this);
    }
    private void configura(){
        WeblafUtils.instalaWeblaf();
        WeblafUtils.configuraWebLaf(jScrollPane1);
        WeblafUtils.configuraWebLaf(jTextField1);
        WeblafUtils.configuraWebLaf(jTextField2);
        WeblafUtils.configuraWebLaf(jTextArea1);
        WeblafUtils.configuraWebLaf(delayField,10);
        WeblafUtils.configuraWebLaf(searchMethodChooser ,7);
        WeblafUtils.configurarBotao(webButton1);
        WeblafUtils.configurarBotao(webButton4);
        WeblafUtils.configurarBotao(webButton5);
        WeblafUtils.configurarBotao(webButton6);
        WeblafUtils.configurarBotao(webButton7);
        jPanel1.setBackground(ColorController.COR_PRINCIPAL);
        jLabel1.setForeground(ColorController.COR_LETRA);
        jLabel2.setForeground(ColorController.COR_LETRA);
    }

    public boolean isbuttonsEnabled() {
        return buttonsEnabled;
    }

    public void setbuttonsEnabled(boolean buttonsBlocked) {
        this.buttonsEnabled = buttonsBlocked;
        webButton1.setEnabled(buttonsBlocked);
        webButton4.setEnabled(buttonsBlocked);
        webButton5.setEnabled(buttonsBlocked);
        webButton6.setEnabled(buttonsBlocked);
        webButton7.setEnabled(buttonsBlocked);
    }
        
    public JPanel getImagePanel(){
        return imagePanel;
    }
    public JTextArea getTextArea(){
        return jTextArea1;
    }
    
    public String getDelay(){
        return delayField.getText();
    }
    
    public String getIDVerticeInicial(){
        return jTextField1.getText();
    }
    public String getIDVerticeFinal(){
        return jTextField2.getText();
    }
    
    public int getSearchMethod(){
        String method = searchMethodChooser.getSelectedItem().toString();
        if(method.equals("Deep First")){
            return SearchAlgorithmFactory.DEEP_FIRST_SEARCH;
        }
        else if(method.equals("Breadth First")){
            return SearchAlgorithmFactory.BREADTH_FIRST_SEARCH;
        }
        else if(method.equals("Dijkstra")){
            return SearchAlgorithmFactory.DIJKSTRA_SEARCH;
        }
        return -1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        delayField = new javax.swing.JTextField();
        webButton7 = new com.alee.laf.button.WebButton();
        webButton6 = new com.alee.laf.button.WebButton();
        webButton5 = new com.alee.laf.button.WebButton();
        searchMethodChooser = new com.alee.laf.combobox.WebComboBox();
        webButton4 = new com.alee.laf.button.WebButton();
        webButton1 = new com.alee.laf.button.WebButton();
        jPanel7 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        imagePanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(73, 40));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setText("Vertice Inicial");
        jPanel5.add(jLabel1, java.awt.BorderLayout.WEST);

        jTextField1.setText("A");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));

        jTextField2.setText("D");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Vertice Procurado");
        jPanel6.add(jLabel2, java.awt.BorderLayout.WEST);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        delayField.setText("1000");
        jPanel3.add(delayField);

        webButton7.setText("Colorir");
        webButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(webButton7);

        webButton6.setText("Planaridade");
        webButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(webButton6);

        webButton5.setText("Conectividade");
        webButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(webButton5);

        searchMethodChooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deep First", "Breadth First", "Dijkstra" }));
        jPanel3.add(searchMethodChooser);

        webButton4.setText("Buscar");
        webButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(webButton4);

        webButton1.setText("Carregar");
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(webButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.9);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(166, 175));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSplitPane1.setBottomComponent(jScrollPane1);

        imagePanel.setOpaque(false);
        imagePanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setTopComponent(imagePanel);

        jPanel7.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void webButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton6ActionPerformed
        controller.planaridade();
    }//GEN-LAST:event_webButton6ActionPerformed

    private void webButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton5ActionPerformed
        controller.conectividade();
    }//GEN-LAST:event_webButton5ActionPerformed

    private void webButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton4ActionPerformed
        controller.search();
    }//GEN-LAST:event_webButton4ActionPerformed

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        controller.readXML();
    }//GEN-LAST:event_webButton1ActionPerformed

    private void webButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton7ActionPerformed
        controller.coloracao();
    }//GEN-LAST:event_webButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField delayField;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private com.alee.laf.combobox.WebComboBox searchMethodChooser;
    private com.alee.laf.button.WebButton webButton1;
    private com.alee.laf.button.WebButton webButton4;
    private com.alee.laf.button.WebButton webButton5;
    private com.alee.laf.button.WebButton webButton6;
    private com.alee.laf.button.WebButton webButton7;
    // End of variables declaration//GEN-END:variables
}
